services:
  db:
    image: postgis/postgis:15-3.3
    container_name: cdn_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: cdn_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  cdn:
    image: cdn_app
    build:
      context: .
    container_name: cdn_app
    env_file:
      - .env-non-dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["app/docker/app.sh"]
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000

volumes:
  postgresdata:
  grafanadata:
  prometheusdata:
